### ISSUE TITLE
Diagrama de casos de uso del Sistema

### ISSUE THREAD

**Issue by FeliRad-sum** [FeliRad-sum/Tarea-2#2]
Identifición de los actores, casos de uso
y sus relaciones

**Comment by ireneGamazo** [comment]
[https://github.com/FeliRad-sum/Tarea-2/blob/main/casos%20de%20usos%202.JPG]()

**Comment by ireneGamazo** [comment]
![casos de usos 2](https://user-images.githubusercontent.com/80349647/118689634-83c5eb00-b807-11eb-9832-183596a0d13f.JPG)
