### ISSUE TITLE
Especificación de los actores del Sistema

### ISSUE THREAD

**Issue by FeliRad-sum** [FeliRad-sum/Tarea-2#3]
1) Fase de inicio:

c. Especificación de los actores del Sistema que se hayan identificado en el 
diagrama de casos de uso, es decir, los diferentes tipos de usuarios y otros 
sistemas con los que deba interactuar el sistema a desarrollar. Se puede 
utilizar la siguiente plantilla:

**Comment by ban1002** [comment]
![image](https://user-images.githubusercontent.com/84398794/119155776-cf6cd480-ba53-11eb-8af8-cce0a54b8f1d.png)

![image](https://user-images.githubusercontent.com/84398794/119155849-e3183b00-ba53-11eb-9667-732ea3bd1767.png)

![image](https://user-images.githubusercontent.com/84398794/119155944-017e3680-ba54-11eb-8c6c-e851578e93ab.png)
