### ISSUE TITLE
Diagrama del Clases general del sistema

### ISSUE THREAD

**Issue by ireneGamazo** [FeliRad-sum/Tarea-2#5]
2) Fase de elaboración:

c. Diagrama de clases general del Sistema completo. No es necesario incluir 
los atributos y métodos de cada clase, únicamente identificar las relaciones, 
su nombre y multiplicidad.

**Comment by ban1002** [comment]
![image](https://user-images.githubusercontent.com/84398794/119165768-224b8980-ba5e-11eb-98fd-fc49fb440d95.png)
