### ISSUE TITLE
Diagrama de secuencias/colaboración

### ISSUE THREAD

**Issue by ireneGamazo** [FeliRad-sum/Tarea-2#7]

**Comment by FeliRad-sum** [comment]
Las diagramas de secuencias se encuentran apartado 2.c del pdf

![image](https://user-images.githubusercontent.com/80574842/119162618-e19e4100-ba5a-11eb-9752-f1867bc28f7a.png)
![image](https://user-images.githubusercontent.com/80574842/119163260-8751b000-ba5b-11eb-931c-47f18b203778.png)
![image](https://user-images.githubusercontent.com/80574842/119163297-90db1800-ba5b-11eb-85e4-d9279272526c.png)
![image](https://user-images.githubusercontent.com/80574842/119163390-a94b3280-ba5b-11eb-8a63-3f19489a1c93.png)

![image](https://user-images.githubusercontent.com/80574842/119163327-99cbe980-ba5b-11eb-94f0-6b61140779ec.png)
![image](https://user-images.githubusercontent.com/80574842/119163454-b5cf8b00-ba5b-11eb-81bb-4c4645a72537.png)
![image](https://user-images.githubusercontent.com/80574842/119163527-c7b12e00-ba5b-11eb-87b2-ba53ce8c1f29.png)
